const Menu = [
    {
        id: 1,
        image: "Images/image1.jpg",
        name: "Meggi",
        category: "breakfast",
        price: "20₹",
        description: "Lorem Ipsum is simply dummy text of the printing.",
    },
    {
        id: 2,
        image: "Images/untitled.jpg",
        name: "Corn",
        category: "evening",
        price: "40₹",
        description: "Lorem Ipsum is simply dummy text of the printing.",
    },
    {
        id: 3,
        image: "Images/untitled1.jpg",
        name: "allu pakoda",
        category: "breakfast",
        price: "70₹",
        description: "Lorem Ipsum is simply dummy text of the printing.",
    },
    {
        id: 4,
        image: "Images/lunch.jpg",
        name: "Gujarati tahli",
        category: "lunch",
        price: "300₹",
        description: "Lorem Ipsum is simply dummy text of the printing.",
    },
    {
        id: 5,
        image: "Images/chawal.jpg",
        name: "Rajma Chawal",
        category: "lunch",
        price: "100₹",
        description: "Lorem Ipsum is simply dummy text of the printing.",
    },
    {
        id: 6,
        image: "Images/img.jpg",
        name: "Pita Bread Pizza",
        category: "dinner",
        price: "200₹",
        description: "Lorem Ipsum is simply dummy text of the printing.",
    },
    {
        id: 7,
        image: "Images/img.jpg",
        name: "Pita Bread Pizza",
        category: "dinner",
        price: "200₹",
        description: "Lorem Ipsum is simply dummy text of the printing.",
    },
    {
        id: 8,
        image: "Images/samosa.jpg",
        name: "Samosa",
        category: "evening",
        price: "30₹",
        description: "Lorem Ipsum is simply dummy text of the printing.",
    },
    {
        id: 9,
        image: "Images/samosa.jpg",
        name: "Samosa",
        category: "evening",
        price: "30₹",
        description: "Lorem Ipsum is simply dummy text of the printing.",
    },
]

export default Menu